repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
        files: ^((custom_components|pylint|script|tests)/.+)?[^/]+\.(py|pyi)$
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint
