---
refresh_all:
get_recipe:
  # target:
  #   entity:
  #     integration: ica
  #     domain: todo
  fields:
    recipe_id:
      name: "Recipe id"
      description: "The id of the recipe to retrieve"
      example: "725608"
      default: '725608'
      required: true
      selector:
        text:
get_baseitems:
  fields:
    integration:
      name: "ICA Account"
      required: true
      selector:
        config_entry:
          integration: ica
add_baseitem:
  fields:
    integration:
      name: "ICA Account"
      required: true
      selector:
        config_entry:
          integration: ica
    identifier:
      name: "Name / Barcode"
      description: "Either a free text name or a Barcode"
      example: "07300400375504"
      default: ''
      required: true
      selector:
        text:
add_offer_to_shopping_list:
  target:
    entity:
      integration: ica
      domain: todo
  fields:
    offer_id:
      name: "OfferId"
      description: "The offer id to add to a shopping list"
      example: "2000681790"
      default: ''
      required: true
      selector:
        text:
    conflict_mode:
      name: "Conflict mode"
      description: "What do to if the item already exists"
      default: 'ignore'
      selector:
        select:
          options:
            - "ignore"
            - "append"
            - "merge"
