get_recipe:
  # target:
  #   entity:
  #     integration: ica
  #     domain: todo
  fields:
    recipe_id:
      name: "Recipe id"
      description: "The id of the recipe to retrieve"
      example: "725608"
      default: '725608'
      required: true
      selector:
        text:
