---
refresh_all:

get_recipe:
  # target:
  #   entity:
  #     integration: ica
  #     domain: todo
  fields:
    recipe_id:
      name: "Recipe id"
      description: "The id of the recipe to retrieve"
      example: "725608"
      default: '725608'
      required: true
      selector:
        text:

get_baseitems:
  fields:
    integration:
      name: "ICA Account"
      required: true
      selector:
        config_entry:
          integration: ica

add_baseitem:
  fields:
    integration:
      name: "ICA Account"
      required: true
      selector:
        config_entry:
          integration: ica
    identifier:
      name: "Name / Barcode"
      description: "Either a free text name or a Barcode"
      example: "07300400375504"
      default: ''
      required: true
      selector:
        text:

add_offers_to_shopping_list:
  target:
    entity:
      integration: ica
      domain: todo
  fields:
    offer_ids:
      name: "OfferIds"
      description: "The offer id(s) to add to a shopping list"
      example: "2000681790, 2000698334"
      default: ''
      required: true
      selector:
        text:
          multiple: true
    conflict_mode:
      name: "Conflict mode"
      description: "What do to if the item already exists"
      default: 'APPEND'
      selector:
        select:
          options:
            - "APPEND"
            - "MERGE"
            - "IGNORE"
