---
name: Validate hassfest

on:
  # push:
  pull_request:
  # schedule:
  #   - cron: "0 0 * * 1"   # https://crontab.guru/#0_0_*_*_1
  workflow_dispatch:

jobs:
  hassfest:
    name: hassfest Action
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "hassfest validation"
        uses: home-assistant/actions/hassfest@master
