---
name: Sync labels

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "34 5 * * *"
  workflow_dispatch:

jobs:
  workflows:
    uses: lazytarget/.github/.github/workflows/labels.yaml@v1.1.0
