---
name: "Lint"

on:
  # push:
  pull_request:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  lint:
    name: Lint
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: "Install requirements"
        run: python3 -m pip install -r requirements.txt

      - name: "Install ruff"
        run: python3 -m pip install ruff

      - name: "Run"
        run: python3 -m ruff check .
