name: release

on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        id: release_drafter
        uses: release-drafter/release-drafter@v6
        with:
          disable-releaser: github.ref != 'refs/heads/main'
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # release-published.yaml (but modified...)
      - name: "Set manifest version number"
        # run: |
        #   python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ github.ref_name }}
        run: |
          python3 ${{ github.workspace }}/.github/scripts/update_hacs_manifest.py --version ${{ steps.release_drafter.outputs.resolved_version }}

      - name: Create zip
        run: |
          cd custom_components/ica
          zip ica.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./custom_components/ica/ica.zip
          asset_name: ica.zip
          # tag: ${{ github.ref }}
          tag: ${{ steps.release_drafter.outputs.resolved_version }}
          overwrite: true