---
name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Release Asset
        uses: "rogerselwyn/actions/release-asset@main"
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          component: "ica"
